### ISSUE TITLE
Error when listing plugins: `the SSL certificate is invalid`

### ISSUE THREAD

**Issue by adamharrison** [lite-xl/lite-xl-plugin-manager#10]
https://github.com/debarchito/lpm/issues/7 @xhxnna .

Not sure what's going on here. I looked into it with the certificate bundle you posted, but can't reproduce at all; seems to work fine for me.

**Comment by adamharrison** [comment]
Can you pull the latest release (v0.9999), and then call 

```
./lpm --ssl-certs=/etc/ssl/ca-certificates/extracted/tls-ca-bundle.pem download https://raw.githubusercontent.com/lite-xl/lite-xl-plugin-manager/master/README.md
```

And let me know if you get an error, or if you see the README.

**Comment by xhxnna** [comment]
Updated and it works, only when manually specifying the bundle though, so yeah its not handling the symlink properly
```
~ ❯ lpm plugin
src/lpm.lua:995: src/lpm.lua:984: git remote fetch error: the SSL certificate is invalid: 0x08 - The certificate is not correctly signed by the trusted CA
~ ❯ lpm plugin --ssl-certs=/etc/ca-certificates/extracted/tls-ca-bundle.pem
                ID |    Version |       Type |     ModVer | Status
------------------ |    ------- |       ---- |     ------ | -----------
        autoinsert |        1.0 |     plugin |          3 | orphan
      bracketmatch |        1.0 |     plugin |          3 | orphan
            exterm |        1.0 |     plugin |          3 | orphan
         formatter |        1.0 |     plugin |          3 | orphan
formatter_prettier |        1.0 |     plugin |          3 | orphan
 formatter_rustfmt |        1.0 |     plugin |          3 | orphan
  formatter_zigfmt |        1.0 |     plugin |          3 | orphan
     language_rust |        1.0 |     plugin |          3 | orphan
     language_toml |        1.0 |     plugin |          3 | orphan
       language_ts |        1.0 |     plugin |          3 | orphan
      language_zig |        1.0 |     plugin |          3 | orphan
          lintplus |        1.0 |     plugin |          3 | orphan
               lsp |        1.0 |     plugin |          3 | orphan
          settings |        1.0 |     plugin |          3 | orphan
```

**Comment by adamharrison** [comment]
It likely didn't actually work, because the error handling around retrieving a repo for the first time isn't perfect, so it likely thinks it got the repo; and didn't try to get it the second time (all listed plugins are plugins on your system, not in repos)

Try ./lpm purge and then ./lpm plugin --ssl-cert=...

You'll see that it'll probably fail again.

Can you try the `download` command specifically? That'll narrow it down. Maybe also try putting `--trace`. So, specifically:

```
./lpm --ssl-certs=/etc/ssl/ca-certificates/extracted/tls-ca-bundle.pem download https://raw.githubusercontent.com/lite-xl/lite-xl-plugin-manager/master/README.md --verbose --trace
```

**Comment by adamharrison** [comment]
So, I'm pretty sure this was because of UB I introduced by accident. This should be working now. If you download latest @xhxnna , it hopefully should work. @ColonelPhantom was also experiencing the same bug, and the new release has fixed it. So I'm going to close this as fixed, but if it's still happening for you, please feel free to reopen.
