### ISSUE TITLE
Doesn't seem to switch to correct branch

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#103]
Using `lpm --ephemeral https://github.com/Guldoman/lite-xl-terminal:PR_fix_scroll_outside terminal`, `lpm` (`v1.2.7-0-g42394ee`) seems to still use the `master` branch.

**Comment by adamharrison** [comment]
Hrm. Seems to be because that branch has a version of 0.9, whereas the `master` version is 1.02. We probably should use the highest version in that case, unless you specify, no?

**Comment by adamharrison** [comment]
`lpm run --ephemeral https://github.com/Guldoman/lite-xl-terminal:PR_fix_scroll_outside terminal:0.9`

Runs as expected.

**Comment by Guldoman** [comment]
> Seems to be because that branch has a version of 0.9, whereas the `master` version is 1.02.

Looks like I just failed to rebase on current `master`...


> We probably should use the highest version in that case, unless you specify, no?

Yeah, that's a sensible behavior.
Maybe a warning would help catching those cases where it's by mistake.

**Comment by adamharrison** [comment]
Done with dd06ba252e662b6f7525e6a88fef3d55326c20c3.
