### ISSUE TITLE
Uninstalling `lsp_rust` causes `language_rust` to be uninstalled as well.

### ISSUE THREAD

**Issue by PerilousBooklet** [lite-xl/lite-xl-plugin-manager#106]
I installed `language_rust` through the meta-package `meta_languages`.
When I try to uninstall `lsp_rust` with `lpm uninstall lsp_rust`, lpm tells me that `language_rust` will also be uninstalled.

**Comment by adamharrison** [comment]
So, I actually can't replicate this.

```
./lpm purge --userdir /tmp/test
./lpm install meta_languages --userdir /tmp/test
./lpm install lsp_rust --userdir /tmp/test
./lpm uninstall lsp_rust --userdir /tmp/test
```

Doesn't trigger it. Can you give me a way to reproduce?
