### ISSUE TITLE
`author` field inconsistencies

### ISSUE THREAD

**Issue by xcb-xwii** [lite-xl/lite-xl-plugin-manager#109]
The spec states that the `author` key is supposed to be placed in `extra`:
https://github.com/lite-xl/lite-xl-plugin-manager/blob/21a64cbc810615d2c74bf2bf38a8f87500eb913e/SPEC.md?plain=1#L76-L81

However, this is contrary to how things actually work, as the `author` field should be outside of `extra` instead.

Also, filtering by author does not seem to work.

**Comment by adamharrison** [comment]
Should be fixed with `ad9af0b`.
