### ISSUE TITLE
Please add a Scoop installation method

### ISSUE THREAD

**Issue by cvladan** [lite-xl/lite-xl-plugin-manager#11]
I've just stumbled across the Lite-XL editor and am delighted.
Obviously, a plugin manager is desperately needed!

To make it easy to install on Windows, please create a Scoop JSON manifest.

I could probably help and do it if you want me to if you are short on time.

**Comment by cvladan** [comment]
... and thank you for the time and effort you have put into the development of this project.

**Comment by adamharrison** [comment]
Hi!

Absolutely, if you want to contribute a manifest that installs a particular plugin/binary, you can do so, and submit it to the lite-xl-plugins repo; I'm not super familiar with scoop but if it's just a matter of downloading a particular binary we'd probably accept it (though it'd have to probably have some integration with lite-xl through a plugin).

**Comment by adamharrison** [comment]
To be clear: if you want to add things to the plugin manager plugin with scoop's list, you could have an extra plugin that hooks the plugin manager's methods, like `PluginView:get_plugins`, to return extra things that are returned from scoop, and then hook `PluginView:install` to install them. Should be doable.

**Comment by adamharrison** [comment]
Sorry, I misunderstood here. You're asking me to add `lpm` to scoop's list of programs that can be installed. Gotcha. In that case, please make the PR yourself, if you can. I'd say use the `latest` release.

**Comment by cvladan** [comment]
Ok. Will do 🙂

**Comment by cvladan** [comment]
I have created a Scoop manifest in JSON format, which can be found on [my Gist page](https://gist.github.com/cvladan/416c1945c9e446a6fc64ba766d6ee4ef).

Could you please review the license, as I am not well-versed in that area.

Feel free to use the JSON from the Gist and include it in the repository, along with instructions on how to use it, which can be summarized in a single sentence - To install lpm using Scoop, user should just run the following command:

```
scoop install https://gist.githubusercontent.com/cvladan/416c1945c9e446a6fc64ba766d6ee4ef/raw/lite-xl-plugin-manager.json
```

Later, you can also submit the manifest directly to the official Extras Scoop bucket, so you don't have to update the manifest file manually with each new version.

**Comment by adamharrison** [comment]
The license is the MIT license.

I'll add the scoop command to the repo readme.

If you'd like to submit the manifest directly to the official extras scoop bucket, please feel free to do so. I don't think it's something I'll maintain myself, but you may absolutely do that if you want to.
