### ISSUE TITLE
Addon type `font` with `path` treated as normal plugin

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#110]
Using https://github.com/gimcnuk/lite-xl-fullbar/blob/008a5aba581dbf287ddf331436571fd43a2df6b6/manifest.json#L16 as an example, running:
```
lpm run --ephemeral https://github.com/gimcnuk/lite-xl-fullbar:main fullbarview --verbose
```
I'm getting:
```
Copying .../.config/lite-xl/lpm/repos/b8403a893394216741a0050c4ab742325ab4750f0154ccff118f88dfbed87d96/main/data/fonts/tabler-icons.ttf to .../.config/lite-xl/lpm/tmp/bottles/dd1cb707f8501fca2fce66ceaa562907738cb8c879eca4540dc96b0016b5a0c0/user/fonts/tabler-icons/init.lua.
```
(`data/fonts/tabler-icons.ttf` -> `user/fonts/tabler-icons/init.lua`)

**Comment by adamharrison** [comment]
There's a number of things fucked up here; but I don't actually even see the copy line. But yes, a straight use of run treats the font as complex for some reason. Will fix whatever's going on here.

**Comment by adamharrison** [comment]
And properly fixed here. https://github.com/lite-xl/lite-xl-plugin-manager/commit/1a8998604561cd4308be8b76cdc12d6d1b0168f2

**Comment by Guldoman** [comment]
Yep, looks good. Thanks!
