### ISSUE TITLE
Font addon installs whole repo if installed as dependency

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#118]
Installing `devicons` from https://github.com/PerilousBooklet/lite-xl-devicons saves the whole repo inside `fonts/font_devicons`.
Installing `font_devicons` directly saves the only `files` entry in `fonts/font_devicons/devicons.ttf`.

(Also we should clarify that the file is installed in the `fonts/plugin_id/` directory somewhere in the spec)

**Comment by adamharrison** [comment]
Should be fixed by a971de3.

**Comment by Guldoman** [comment]
Fixed by 1564bb1ca6570868bbf45c896d679ac45c73fbdc. Thanks!
