### ISSUE TITLE
Scoop install no longer works.

### ISSUE THREAD

**Issue by DryToa5t** [lite-xl/lite-xl-plugin-manager#128]
I tried the scoop install script.  scoop install https://gist.githubusercontent.com/cvladan/416c1945c9e446a6fc64ba766d6ee4ef/raw/lite-xl-plugin-manager.json

It no longer works.  There are lots of other ways I can install it, but I wanted to let someone who maintains the readme know.

**Comment by adamharrison** [comment]
This actually just got merged! Master should now have a proper scoop  manifest here: https://github.com/lite-xl/lite-xl-plugin-manager/blob/master/lite-xl-plugin-manager.json

**Comment by maksimaliabyshev** [comment]
@adamharrison something changed on github, the old link is not giving the json correctly 
needs change link in README.md
```
https://raw.githubusercontent.com/lite-xl/lite-xl-plugin-manager/refs/heads/master/lite-xl-plugin-manager.json
```

**Comment by adamharrison** [comment]
Sure, will make that change.

**Comment by adamharrison** [comment]
Done.

**Comment by adamharrison** [comment]
Anyway, @DryToa5t please reopen if there are any issues with this.
