### ISSUE TITLE
Can't install plug-in: src/lpm.lua:1563: can't find addon PLUGIN_NAME mod-version: 3.0.0

### ISSUE THREAD

**Issue by milen-prg** [lite-xl/lite-xl-plugin-manager#13]
Can't install any plugin from [](https://github.com/lite-xl/lite-xl-plugins), always returns this error:

lpm.x86_64-windows.exe install PLUGIN_NAME
src/lpm.lua:1563: can't find addon PLUGIN_NAME mod-version: 3.0.0

Windows 10 Pro 64bit, all last updates.

**Comment by adamharrison** [comment]
Try 
./lpm.x86_64-windows.exe purge
./lpm.x86_64-windows.exe update --verbose
./lpm.x86_64-windows.exe install bracketmatch

And then paste the log here.

**Comment by milen-prg** [comment]
Where is the log?
This is the result:

C:\Users\mlap\Downloads>lpm.x86_64-windows.exe purge
Removed C:\Users\mlap\.config\lite-xl\lpm.

C:\Users\mlap\Downloads>lpm.x86_64-windows.exe update --verbose
....
t   2.4 MB [   1.0 MB/s][100%]: Fetching https://github.com/adamharrison/lite-xl-plugin-manager.git:lat   2.4 MB [   1.0 MB/s][100%]: Fetching https://github.com/adamharrison/lite-xl-plugin-manager.git:lat   2.4 MB [   1.0 MB/s][100%]: Fetching https://github.com/adamharrison/lite-xl-plugin-manager.git:latest...
   1.2 MB [ 748.2 kB/s][100%]: Fetching https://github.com/lite-xl/lite-xl-plugins.git:master...
  94.7 kB [ 957.7 kB/s][100%]: Fetching https://github.com/lite-xl/lite-xl-colors.git:master...
warning: Can't find manifest.json for https://github.com/lite-xl/lite-xl-colors.git:master; automatically generating manifest.
Updated https://github.com/lite-xl/lite-xl-plugins.git:master
Updated https://github.com/lite-xl/lite-xl-colors.git:master
Updated https://github.com/adamharrison/lite-xl-plugin-manager.git:latest

C:\Users\mlap\Downloads>lpm.x86_64-windows.exe install --verbose bracketmatch
Installing singleton plugin located at C:\Users\mlap\.config\lite-xl\lpm\repos\b13bf2e26f03d19f8a72b22e0bde2c6e7149ef638190b542f0eefd4f70bb3589\master\plugins\bracketmatch.lua to C:\Users\mlap\.config\lite-xl\plugins\bracketmatch.lua
Copying C:\Users\mlap\.config\lite-xl\lpm\repos\b13bf2e26f03d19f8a72b22e0bde2c6e7149ef638190b542f0eefd4f70bb3589\master\plugins\bracketmatch.lua to C:\Users\mlap\.config\lite-xl\plugins\bracketmatch.lua

And after all, again:

C:\Users\mlap\Downloads>lpm.x86_64-windows.exe install plugin-manager
src/lpm.lua:1563: can't find addon plugin-manager mod-version: 3.0.0

P.S. I want to place plugin-manager to can visually install plugins.

**Comment by adamharrison** [comment]
Yeah, that's the log, perfect.

So it does look like it was successful in installing bracketmatch.

For plugin manager, try `lpm.x86_64-windows.exe install plugin_manager`

**Comment by milen-prg** [comment]
Oh, yes, this works, I simply take the names from [](https://github.com/lite-xl/lite-xl-plugins) and did not try for misspelling.
Thank you, very much, for fast support!
