### ISSUE TITLE
Support building native plugins from source

### ISSUE THREAD

**Issue by Jan200101** [lite-xl/lite-xl-plugin-manager#133]
what it says on the tin, useful for the very paranoid and linux distros since intercompatibility between various distros is impossible (especially when linking against shared objects).

Would help help get lpm into distributions due to more control over the build path

My proposal is adding a new entry into the files array that looks something like this:

```json
{
  "arch": "source",
  "checksum": "a215aafbfbf5881ffb3c81e6feb1e5ef28c3310422c8d2be9563c8f616a5804b",
  "url": "https://github.com/adamharrison/lite-xl-terminal/archive/refs/tags/v1.06.tar.gz",
  "commands": [
      "./build.sh"
  ]
  "files": ["libterminal.so"]
}
```

commands and files would be relative to the extracted archive
commands are executed in order and if any of them returns a non 0 return value the whole process is terminated
I'm on the fence between making files just a singular entry, but a plugin may want to install a shared object and another lua plugin that interfaces with it.

**Comment by Jan200101** [comment]
I'm aware that this process would not really function on windows but for setups like meson or cmake it should work out of the box

its really only intended for Linux and paranoid people

**Comment by adamharrison** [comment]
This already exists; as per your request from a few years back, `--post`; documented under dangerous flags. See the help or SPEC.md.

**Comment by adamharrison** [comment]
Correct. Any commands run are in addition, not as a replacement for. 

If we start omitting steps we'll have to do much more than a simple command array.

**Comment by Jan200101** [comment]
so this isn't a "build from source" field, its a "run this extra command after downloading" field.

What I am looking for is a replacement for downloading the shared object and instead building it from source

**Comment by Guldoman** [comment]
You could just overwrite the file with the commands. Or the file could be marked as optional.

In the end this is not really a "supported" way of using the plugin manager.

**Comment by Jan200101** [comment]
Sure, its not needed, just something I consider a nice to have.

To continue the pip comparison, think of it as how wheels are managed: by default it downloads the wheel for your appropriate target but if none are found or if the user explicitly requests it, it attempts to build it from source.

**Comment by adamharrison** [comment]
I am OK with adding a field in `extra` here under `files` (`files`.`extra`.`compile`, maybe?); but I don't think we should focus too much on this; we should instead provide binaries when possible.

**Comment by Jan200101** [comment]
I agree that binaries should be the focus, I just worry about systems where the provided binary is incompatible (e.g. musl systems) or where no binary is provided.

I think having 1 entry for compile is good enough
