### ISSUE TITLE
Moving several fields in the manifest spec into extras?

### ISSUE THREAD

**Issue by Delta-official** [lite-xl/lite-xl-plugin-manager#14]
To be precise: `name`, `description`, `tags`. They won't used in the installation logic, thus rendering them "bloat" (not sure if there's a better way to word this). In my opinion `extras` should be used for any fields that are not directly used for plugin installation/management.

**Comment by Guldoman** [comment]
`extras` should be for fields that are not in the spec, things that package managers are experimenting with.

For example it could contain plugin rating, number of downloads, etc. which are things that are not in the spec, but would allow package managers that don't know about them to just ignore them, while experimental package managers and frontends could make use of.
The idea is that fields in `extra` that become "mainstream" should be introduced in the spec.

**Comment by adamharrison** [comment]
To put things down canonically, I am OK with either interpretation. I like the leanness of Delta's idea, but I also see where Guldo is coming from. Does anyone else have any other thoughts?

**Comment by adamharrison** [comment]
Since there's comment here; and it's basically 1-1, I'm going to close this for now. If this becomes an issue in future, we can reopen, but for now, it seems like the system is working well enough, for now; and may as well not change it if there's no overwhelming desire in either direction.
