### ISSUE TITLE
lpm lite-xl uninstall deletes the installation

### ISSUE THREAD

**Issue by takase1121** [lite-xl/lite-xl-plugin-manager#147]
I was trying to find a way to remove lite-xl from `lpm lite-xl list` and tested `lpm lite-xl uninstall 2.1.6`. lpm removed my installation files with no warning. If this is the intended behavior, it should at least prompt me (of course assuming `--assume-yes` is not given), before deleting it.

![image](https://github.com/user-attachments/assets/a1705c83-9872-4cf8-be81-32ec13a9f389)

**Comment by adamharrison** [comment]
Yeahhhh; probably should prompt. Done. f6f8ff1.
