### ISSUE TITLE
Uninstall non-explicitly installed dependencies when uninstalling plugins

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#17]
For example while installing the `settings` plugin, `widget` is installed too because it's a dependency.
As `widget` wasn't explicitly installed, when `settings` is uninstalled, `widget` should be uninstalled too if it's not needed by any other plugin.

**Comment by adamharrison** [comment]
Yeah, I'll set it to maintain a list of plugins (and also condense `locals.json` and `repos` into a single json file), so that we have a unified 'state' file.

**Comment by adamharrison** [comment]
Wait, this already happens. It prompts you, though.

**Comment by adamharrison** [comment]
Should be fixed, in theory.
