### ISSUE TITLE
(win32) lpm_stat(): attempting to deallocate value in lua state

### ISSUE THREAD

**Issue by 13k** [lite-xl/lite-xl-plugin-manager#19]
[Here](https://github.com/lite-xl/lite-xl-plugin-manager/blob/74ced2030dc40b59b0ebce42269780c2f11afb6d/src/lpm.c#L241), `abs_path` is a pointer to a string [owned by the lua state](https://github.com/lite-xl/lite-xl-plugin-manager/blob/74ced2030dc40b59b0ebce42269780c2f11afb6d/src/lpm.c#L78).

[Later](https://github.com/lite-xl/lite-xl-plugin-manager/blob/74ced2030dc40b59b0ebce42269780c2f11afb6d/src/lpm.c#L254), `lpm_stat()` tries to unconditionally deallocate `abs_path` (covering the POSIX `realpath(3)` allocation case).

I believe the deallocation should be behind a `#ifndef _WIN32` guard, otherwise lpm crashes when `lpm_stat()` is called on windows.

**Comment by adamharrison** [comment]
You're absolutely correct. That's a new free I put in recently to plug a memory hole, and didn't consider the windows path. Will refactor tonight.

**Comment by adamharrison** [comment]
OK, https://github.com/lite-xl/lite-xl-plugin-manager/commit/872b66996c6423a85ddccc905ce7382caa9264a7 should fix it. Can you confirm, and let me know?

**Comment by 13k** [comment]
It seems to be fixed. Thanks for extremely quick response and fix!
