### ISSUE TITLE
`lpm` does not work outside of source directory

### ISSUE THREAD

**Issue by bingis-khan** [lite-xl/lite-xl-plugin-manager#2]
`lpm` does not work outside of source directory:

```
> lpm
internal error when starting the application: cannot open src/lpm.lua: No such file or directory
```

Same thing when installing with pacman from AUR and compiling from source. Is this expected behavior?

**Comment by adamharrison** [comment]
You want to build it with -DLPM_STATIC=1.

That was previously the default, but due to some changes, it's now an opt-in thing.

I'll adjust the readme.

**Comment by adamharrison** [comment]
Also, please note, `lpm` is not 1.0 yet; so shouldn't be expected to work in all cases, I'm still banging away on it. Should be a proper 1.0 soon.
