### ISSUE TITLE
Question: addon version limitations

### ISSUE THREAD

**Issue by SwissalpS** [lite-xl/lite-xl-plugin-manager#22]
the spec states version can be a string containing 0 to 9 and dot.

would "20230512.231211" be a problem as addon version? According to spec it is not, but a friend isn't sure.

Edit: link to spec https://github.com/lite-xl/lite-xl-plugin-manager/blob/master/SPEC.md#:~:text=version%3A%20The%20addon%27s%20semantic%20version.%20A%20string%20that%20can%20contains%20%5B0%2D9%5C.%5D

**Comment by adamharrison** [comment]
According to spec it is fine. `lpm` will interpret this correctly. It is odd, and not really the format that's used by other plugins, but will work.
