### ISSUE TITLE
git remote fetch error: authentication required but no callback set

### ISSUE THREAD

**Issue by Jan200101** [lite-xl/lite-xl-plugin-manager#26]
Full error:
```
src/lpm.lua:1158: src/lpm.lua:1142: git remote fetch error: authentication required but no callback set
```

This appears to be caused by this part of my .gitconfig

```gitconfig
[url "ssh://git@github.com/"]
        insteadOf = https://github.com/
```

**Comment by adamharrison** [comment]
I'm not adding in ssh support, so I'll see if I can't tell it to ignore local system configuration for this.

**Comment by adamharrison** [comment]
Only if you build it with libssh too, which I don't. 

Either way, SPEC specifies https accessible.

**Comment by Jan200101** [comment]
huh, I like against system libgit2, which should have those capabilities.

**Comment by adamharrison** [comment]
Probably requires a different config setup in the code.
