### ISSUE TITLE
how to install to use graphically as in the picture

### ISSUE THREAD

**Issue by milen-prg** [lite-xl/lite-xl-plugin-manager#30]
How to install the plugin manager, to use it graphically as in the picture, inside the Lite-xl environment GUI?
I use Windows 10.

**Comment by adamharrison** [comment]
We'll be releasing it in the next version of lite bundled up; so in future you won't have to worry about grabbing it, but for now, download this https://github.com/lite-xl/lite-xl-plugin-manager/releases/download/v1.0.5/lpm.x86_64-windows.exe, and then in your command line, do `lpm.x86_64-windows.exe install plugin_manager`. That should do it.

**Comment by milen-prg** [comment]
Thank you!
