### ISSUE TITLE
Issue with lpm failing in Windows 10 OS. Might be because of PATH has white space. 

### ISSUE THREAD

**Issue by FourtyThree43** [lite-xl/lite-xl-plugin-manager#31]
Description:
```
 .\lpm install black
10.6 kB [ 247.6 kB/s][100%]: Fetching https://git.sr.ht/~tmpod/black-lite:2a1ab1b703f954edb39efb73e72b44c0d18b30a2...
src/lpm.lua:1158: src/lpm.lua:448: can't rename file C:\Users\Carter V\.config\lite-xl\lpm\tmp\tranient-repo to C:\Users\Carter V\.config\lite-xl\lpm\repos\78901d322be2d43822c5532950cf701a6914c934d28837f1c7425177a9bf4152\2a1ab1b703f954edb39efb73e72b44c0d18b30a2: File exists
```

Observed that it works when I manually create the destination (dst) path then run it again.

**Comment by adamharrison** [comment]
But yes, you're probably right, could be a whitespace thing.

**Comment by FourtyThree43** [comment]
I reproduced it still persist.

```
Administrator in ~\Desktop\Lua53 via  v5.4.2
❯ .\lpm purge
Purged C:\Users\Sparta V\.config\lite-xl\lpm.

Administrator in ~\Desktop\Lua53 via  v5.4.2 took 9s
❯ .\lpm install black
   2.5 MB [ 860.4 kB/s][100%]: Fetching https://github.com/adamharrison/lite-xl-plugin-manager.git:latest...
src/lpm.lua:1158: src/lpm.lua:448: can't rename file C:\Users\Carter V\.config\lite-xl\lpm\tmp\tranient-repo to C:\Users\Carter V\.config\lite-xl\lpm\repos\4d1849c9a6a9b5aa584d1b3a11a9e14fd4e8929b154884fe33a8e96a795ef379\latest: File exists
```

**Comment by adamharrison** [comment]
OK, perfect. That means it should be relatively easy to reproduce. I don't have access to my windows machine at present (am moving), but I'll try and repro this with wine, and see if I can't get it working. As you say it's almost assuredly a problem with the space.

**Comment by adamharrison** [comment]
Oho. No. It's actually just broken on windows in general; fails in wine even without spaces. Odd. Wonder when that happened. Will fix.

**Comment by adamharrison** [comment]
Got it, @FourtyThree43 , try https://github.com/lite-xl/lite-xl-plugin-manager/commit/966bd543565beb00c36e4cd1ecaf4aac3b24c7ea.
