### ISSUE TITLE
Create a scoop manifest

### ISSUE THREAD

**Issue by geetmankar** [lite-xl/lite-xl-plugin-manager#44]
Hi, wanted to know if the creators can make a `scoop` manifest for their releases, now that the continuous release does not work well with @cvladan's scoop manifest.

His manifest is linked [here](https://gist.github.com/cvladan/416c1945c9e446a6fc64ba766d6ee4ef#file-lite-xl-plugin-manager-json)

**Comment by adamharrison** [comment]
Honestly, I'd prefer to not really maintain an "official" scoop installer. Ideally we can just get by with the normal build system we have, plus binaries. 

If someone else wants to add in support for different package types like `.deb`, `.rpm`, `snap`, or different installers like `scoop`; then I've got no issue with it, but I think we should remain roughly agnostic with regards to this type of thing, unless lite itself gets support for those things.

I don't have any issue linking them from the README and whatnot; but maintaining them is probably a bridge too far (at least for me, at this time).

If you wanna make a PR to his manifest, please, feel free!
