### ISSUE TITLE
Managing local repos without manifest throws error

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#47]
Trying to `lpm repo add` a local repository without a `manifest.json` file throws `lite-xl-plugin-manager/src/lpm.lua:1061: requires an instantiation`.

Moreover if a local repository is added successfully, but then its manifest is removed, `lpm` fails to do most operations, throwing the same error.

**Comment by adamharrison** [comment]
OK, this should be fixed now.

**Comment by adamharrison** [comment]
Re-open if not fixed.
