### ISSUE TITLE
Possible issue in `PluginManager:get_addons`

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#51]
https://github.com/lite-xl/lite-xl-plugin-manager/blob/8f2cd874ddc57793a08a9b6bdb5172c25802a5e0/plugins/plugin_manager/init.lua#L191

`options` is always `nil` there.

**Comment by adamharrison** [comment]
OK, passed around options in all cases. Close if fixed.

**Comment by adamharrison** [comment]
Re-open if not fixed.
