### ISSUE TITLE
`lpm run` plugins from repos with only an `init.lua`

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#58]
Currently the generated manifest is lacking any plugin, and doesn't allow running the plugin.
For example a repo with:
```
lite-xl-plugin-name
└──init.lua
```
doesn't work with `lpm run https://repo/url:master`, or `lpm run https://repo/url:master lite-xl-plugin-name` or  `lpm run https://repo/url:master plugin-name`.

**Comment by adamharrison** [comment]
OK, should be fixed now.

**Comment by adamharrison** [comment]
Actually, re-open if not-fixed.
