### ISSUE TITLE
Allow passing parameters to Lite XL

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#62]
For example with `lpm run pluginname -- param1 param2`, `param1` and `param2` would be passed as parameters to Lite XL.

**Comment by adamharrison** [comment]
This already exists; and is exactly that syntax.

**Comment by Guldoman** [comment]
Oh yeah, you're right. I'm just getting bad results with spaces.
For example `lpm run -- 'a b' c\ d` will open `a` `b` `c` and `d`, not `a b` `c d`.

**Comment by adamharrison** [comment]
Oh interesting. I'm assuming that doesn't happen with normal lite; just through lpm? If so, yeah; open an issue.
