### ISSUE TITLE
Allow masking plugins to avoid installing them

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#63]
Masking a plugin removes it from any operation that it's involved in.

For example `lpm install lsp --mask settings --mask snippets` will install `lsp` but avoid installing/updating `settings` and `snippets`.
Or even `lpm uninstall lsp --mask lsp_snippets` will remove `lsp` with all the unneeded dependencies, while keeping `lsp_snippets` installed.

**Comment by adamharrison** [comment]
Something like this what you have in mind? https://github.com/lite-xl/lite-xl-plugin-manager/tree/PR/masking

**Comment by Guldoman** [comment]
Yeah looks good.
Maybe it should log the skipped operations tho.

**Comment by adamharrison** [comment]
Yeah, ok. Will add them as warnings.

**Comment by adamharrison** [comment]
Ok, done.
