### ISSUE TITLE
Passing arguments with spaces to Lite XL isn't handled correctly

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#64]
For example `lpm run -- 'a b' c\ d` will open `a` `b` `c` and `d`, not `a b` `c d`.

My guess is that `'a b' c\ d` gets passed to `lpm` as
```
a b
c d
```
But this is then concatenated into a single string and executed via
https://github.com/lite-xl/lite-xl-plugin-manager/blob/1feceeabd86785c8edb291143edaeace9d2be22b/src/lpm.lua#L1393

So it results in
```
path_to_exe a b c d
```

This also means that shell "stuff" gets re-interpreted.
For example `lpm run -- '$PWD'` will open the current dir, instead of the file `$PWD`.

**Comment by Guldoman** [comment]
> Outputs `$PWD`.

Yeah, but LPM will do the opposite.

**Comment by adamharrison** [comment]
Ah yes, sorry misunderstood. Will ALSO fix itself with appropriate quoting.

**Comment by adamharrison** [comment]
How's bda93eb treating you?

**Comment by Guldoman** [comment]
Seems to work great if there aren't any `\`, but completely breaks otherwise.
Big improvement tho.

**Comment by adamharrison** [comment]
Oof. I tried c\ d and it worked fine. What specifically broke for you?

**Comment by adamharrison** [comment]
Oh, yeah; I guess it would break, woudln't it if you did `c\\d`. I guess I'll fix that.
