### ISSUE TITLE
Error when installing/running multiple plugins that depend on each other

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#67]
When installing/running multiple plugins, and one of those has a dependency on one that is being explicitly installed, `lpm` fails with `addon <name> is already installed`.

So for example `lpm run settings lsp` raises `addon settings is already installed`, as `lsp` depends on `settings`.

**Comment by adamharrison** [comment]
Should be fixed with f264efb.

**Comment by Guldoman** [comment]
Yup fixed, thanks!
