### ISSUE TITLE
Fails to uninstall any plugin with a core dependency

### ISSUE THREAD

**Issue by Gaspartcho** [lite-xl/lite-xl-plugin-manager#71]
When uninstalling a plugin with an orphan dependency, lpm tries to uninstall it, even if this dependency is core. However, because it is core, is doesn't uninstall it and just does not do anything.

![image](https://github.com/lite-xl/lite-xl-plugin-manager/assets/93390411/fd9c5188-1f0a-4eed-aafc-297716f5c93a)

In the case where I say to not uninstall the dependency, it doesn't uninstall anything either.

![image](https://github.com/lite-xl/lite-xl-plugin-manager/assets/93390411/e0016912-0150-4db2-8d88-8c0106974233)

**Comment by adamharrison** [comment]
I tell a lie; was able to still have issues trying to `lpm uninstall lintplus`; eventually language_js is trying to be uninstalled. Weird. Will look more into.

**Comment by adamharrison** [comment]
Nope, I tell *another* lie; forgot to pull the new master branch lol. Sorry for confusion. This is fixed.
