### ISSUE TITLE
Ephemeral bottles should have a different hash than normal ones

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#75]
To avoid accidentally removing a non-ephemeral bottle.

**Comment by adamharrison** [comment]
I mean, in theory, bottles are specifically marked as ephemeral in ram, and deleted at the end of a run. They won't get deleted as part of a clean-up procedure or anything.  In that case, what's the advantage of having a separate naming scheme?

**Comment by Guldoman** [comment]
Say I run
```
lpm run 2.1.2-gh plugin_manager
```
and change something in the user module.
I expect that running the same command again I will still find the changes I made to the user module.

No I also run
```
lpm run 2.1.2-gh --ephemeral plugin_manager
```
then close the relative Lite XL instance.

Now the original, non-ephemeral bottle is gone, bringing with it my user module changes.

**Comment by adamharrison** [comment]
Ah. Gotcha. Makes sense. Yeah we should include bottle options in there. Will look into.

**Comment by adamharrison** [comment]
OK, try 55bd397.

**Comment by Guldoman** [comment]
Yep looks good.
Minor inconvenience is that the hash is not backward compatible.

**Comment by adamharrison** [comment]
22597dd
