### ISSUE TITLE
`update-checksums` doesn't seem to do anything

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#78]
After changing the urls in a manifest (in a `files` section) and running `lpm update-checksums manifest.json`, I'm not getting any output and the manifest doesn't update.
It terminates very quickly, so I don't think it's even downloading the new files.

Specifying the plugin name as last parameter doesn't change the outcome.

**Comment by adamharrison** [comment]
How dare it.

**Comment by adamharrison** [comment]
Honestly, it seems to work for me when I add a bogus checksum `plugin_manager`'s files array for the x86_64-android android file ,and then run

```
lpm update-checksums manifest.json plugin_manager
```

Can you attach the specific manifest it's having issues with?
```

**Comment by Guldoman** [comment]
Steps to reproduce:
```
wget https://github.com/adamharrison/lite-xl-lsp-servers/raw/69c85033c8a62214d1e758d986cb2eea7a66728e/manifest.json
sed -i 's\2023-10-09\2024-02-19\g' manifest.json
sed -i 's\20231009\20240219\g' manifest.json
sha256sum manifest.json > checksum
lpm update-checksums manifest.json lsp_rust
sha256sum manifest.json | cmp - checksum
```

**Comment by adamharrison** [comment]
Yeah, super odd. OK. Looking into.

**Comment by adamharrison** [comment]
Ah. It's because the manifest is deprecated, and using `plugins` instead of `addons` as its primary key. There is some backwards compatibility, but not with this new command.

Let's rename it to `addons`.

**Comment by adamharrison** [comment]
Should be fixed as of https://github.com/adamharrison/lite-xl-lsp-servers/commit/b04f4a57ef28f3146d949dfc8b7809d401cb79b5.

**Comment by Guldoman** [comment]
Yup, that works, thanks!
