### ISSUE TITLE
`git remote fetch error: ...` when using `lpm update`

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#85]
I'm getting
```
$ lpm update
Updating https://github.com/lite-xl/lite-xl-plugins.git:master...
Updating https://github.com/lite-xl/lite-xl-colors.git:master...
git remote fetch error: object not found - no match for id (51f89bcc8a6f3f0f3f36788f5559f2d3e38788f1)
```
With this `repos` directory:
[repos_bad.zip](https://github.com/lite-xl/lite-xl-plugin-manager/files/14413041/repos_bad.zip)

But if I remove it and update again everything works fine:
[repos_good.zip](https://github.com/lite-xl/lite-xl-plugin-manager/files/14413049/repos_good.zip)

**Comment by adamharrison** [comment]
I dunno how to solve this. I can repro, but literally no fetch option seems to make a difference. It's failing at `git_remote_download`. Even if I tell it to fetch with no refespec, and set all `fetch_opts` to basically do a maximum fetch, it still breaks.

Best I can do would be to simply delete the old repo, and start again. Maybe I'll do that? Lemme try...

**Comment by adamharrison** [comment]
I mean it's hacky as fuck, but: 589dbc8.

**Comment by Guldoman** [comment]
Seems to work well enough, thanks!
