### ISSUE TITLE
Can't specify multiple filters of the same type

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#87]
For example
```
lpm list --status=installed --status=upgradable
```
will only list `upgradable` plugins.

**Comment by adamharrison** [comment]
Should be closed with 3c38703.

**Comment by Guldoman** [comment]
Seems to still be a problem with other kinds of filters like `--type` and `--name`.

**Comment by adamharrison** [comment]
Fixed with 35fb42b.

**Comment by Guldoman** [comment]
Looks good, thanks!
