### ISSUE TITLE
Complex plugins installed with .lua extension

### ISSUE THREAD

**Issue by jgmdev** [lite-xl/lite-xl-plugin-manager#9]
**LPM Version**: 0.9994-1-gc73f371-x86_64-linux

## Description

When installing a complex plugin from lite-xl-plugins like `editorconfig`, it gets installed to `/plugins/editorconfig.lua`

## Expected Result

`plugins/editorconfig` should be installation path

## Unexpected Result

`plugins/editorconfig.lua` the `.lua` extension is appended to the directory name of the plugin.

**Comment by adamharrison** [comment]
v0.9995 should fix, added to test suite.
