### ISSUE TITLE
File hashes are improperly used

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#92]
If a `file` entry in a manifest has an hash, and we have the hash in cache, the file is used without checks.
So if the file should have been different, and should have failed the hash check, it still uses the cached version.

If a `file` entry in a manifest has a bad hash, and the hash is not in cache, the file is saved with the bad hash, and `lpm` exits with an hash check failure.
If the same command is executed again, the hash is not checked and the bad file is used.

**Comment by adamharrison** [comment]
This should actually be fixed with new release; confirm?

**Comment by Guldoman** [comment]
Works way better, but can still be abused by adding `.part` to the hash after it's already been downloaded.

**Comment by adamharrison** [comment]
Should be fixed.

**Comment by Guldoman** [comment]
Seems like you can still use the hash of another already-downloaded file.

**Comment by adamharrison** [comment]
:hooty_angry:

**Comment by adamharrison** [comment]
92b11ba?

**Comment by Guldoman** [comment]
Seems to work!
So now it uses the url hash as filename, right?

**Comment by adamharrison** [comment]
Yup; and will do an extra check.
