### ISSUE TITLE
Support OpenSSL

### ISSUE THREAD

**Issue by iahung2** [lite-xl/lite-xl-plugin-manager#97]
Please update `lpm.c` to support OpenSSL. Thank you.

**Comment by adamharrison** [comment]
Out of curiosity, why? What's wrong with mbedtls?

**Comment by iahung2** [comment]
> Out of curiosity, why? What's wrong with mbedtls?

OpenSSL is always there as a fallback solution. It's good to have support for it.

**Comment by adamharrison** [comment]
I suppose, but given that the exact commit of mbedtls is submoduled and statically compiled into LPM, it doesn't strike me there'll be too many issues, no?

I originally tried to use OpenSSL but it ends up ballooning the compile times as well as the file size, so mbedtls made a lot more sense, and seems to do the job. 

If there a specific instance that you've run into that mbedtls is not appropriate for it, I'd definitely look into adding it, but as it stands, I don't really see a reason for it.

**Comment by iahung2** [comment]
> I suppose, but given that the exact commit of mbedtls is submoduled and statically compiled into LPM, it doesn't strike me there'll be too many issues, no?
> 
> I originally tried to use OpenSSL but it ends up ballooning the compile times as well as the file size, so mbedtls made a lot more sense, and seems to do the job.
> 
> If there is a specific instance that you've run into that mbedtls is not appropriate for, I'd definitely look into adding it, but as it stands, I don't really see a reason for it.

You are stuck with MbedTLS2. You can't move to MbedTLS3, as Libgit2 doesn't support it. MBedTLS2 is deprecated. MSYS2 no longer has packages for it. Compiling MbedTLS2 from source (using your submodule, of course) is currently failing on MSYS2.

OpenSSL is large. But the advantage of it is that it will always be there. All Linux distributions, BSDs, macOS, etc. have packages for it. Most of the time, you don't have to build OpenSSL from source!

It will be a bit problematic on Windows, but OpenSSL is only an alternative backend. The default is still MbedTLS. This can be done with some preprocessor and a new option in `meson_options.txt`.

**Comment by adamharrison** [comment]
> You are stuck with MbedTLS2. You can't move to MbedTLS3, as Libgit2 doesn't support it. MBedTLS2 is deprecated. 

So, this is quite a salient point; and is a good reason to support OpenSSL. Let me check on what the status on MbedTLS3 integration (if any) on libgit2 is. If there's no PR, or anything like that, then yeah; I suppose it does make sense to support OpenSSL, even though I am loathe to do it.

> MSYS2 no longer has packages for it. Compiling MbedTLS2 from source (using your submodule, of course) is currently failing on MSYS2.

This is the primary way I compile `lpm` on windows, and it works fine for me. What error are you receiving?

> OpenSSL is large. But the advantage of it is that it will always be there. All Linux distributions, BSDs, macOS, etc. have packages for it. Most of the time, you don't have to build OpenSSL from source!

Ideally, I like to simply statically link in a particular commit in order to ensure that things are the same for everyone; so I would prefer to keep that broad model, in general.

> It will be a bit problematic on Windows (without MSYS2), but OpenSSL is only an alternative backend. The default is still MbedTLS. This can be done with some preprocessor in lpm.c and a new option in meson_options.txt.

Yes; if I do add it, it'll be a preprocessor define; likely `LPM_OPENSSL`.

**Comment by adamharrison** [comment]
Also, I just checked, and I don't actually see a note about mbedtls2 being deprecated. Can you share where you found that?

**Comment by iahung2** [comment]
> Also, I just checked, and I don't actually see a note about mbedtls2 being deprecated. Can you share where you found that?

https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.7

> Mbed TLS 2.28 is a long-time support branch. It will be supported with bug-fixes and security fixes until end of 2024.

Deprecated or not, the only thing I know is that it doesn't build on MSYS2, and MSYS2 removed the packages for it. Such a thing will never happen with OpenSSL because OpenSSL is the standard.

**Comment by adamharrison** [comment]
> Deprecated or not, the only thing I know is that it doesn't build on MSYS2, and MSYS2 removed the packages for it. Such a thing will never happen with OpenSSL because OpenSSL is the standard.

But... I can build on MSYS2? Again; that's primarily how I build my Windows copy of lpm. What errors are you getting?

**Comment by adamharrison** [comment]
So, I installed clang64, set up the environment, and just tried to compile mbedtls, and does produce the appropriate static library. There are some other issues with libzip and whatnot, but they are unrelated to mbedtls or libgit2.

Can you let me know the error you're hitting? Are you using the build.sh script, or meson?

**Comment by iahung2** [comment]
Both `meson setup build` and `meson setup build -Dstatic=true` failed with the same error. It said it couldn't find MbedTLS. `static` option has no effect. I have to edit `meson.build`.

`./build.sh` without any options worked. I have no idea why! I ignored this script from the beginning. I used to have a quick look at it. I don't understand how it's working. There is no `CMakeLists.txt` on the root of the repo, but it still invokes `cmake`. I think it's a leftover when the project still uses `cmake` and ignores it. Most projects I know don't employ `meson` from the beginning.

**Comment by adamharrison** [comment]
So, `build.sh` is the official way of building `lpm`. The meson stuff is just there so it's easier to build for arch; it's not actually maintained by me. It doesn't actually use any of the submodules yet, as that's apparently somewhat complicated with meson, see #81 .

So, yeah; I'd say just try using `build.sh` when you're building going forward.

**Comment by Guldoman** [comment]
> `static` option has no effect. I have to edit `meson.build`.

That option is about embedding Lua source into the executable, as described in https://github.com/lite-xl/lite-xl-plugin-manager/blob/f677376167b401b2c8f9154ac30fcd21b8aff238/meson_options.txt#L1

> There is no `CMakeLists.txt` on the root of the repo, but it still invokes `cmake`. I think it's a leftover when the project still uses `cmake` so I ignored it.

Cmake stuff is there to build the submodules that require it.
